version: "2.2"

services:
  db:
    env_file:
      - env_dev
    build:
      context: ../polisDatabase
    expose:
      - 5432
    networks:
      polis:
        ipv4_address: 192.168.1.4
#    networks:
#      - polis

  server:
    env_file:
      - env_dev
    build:
      context: ../polisServer
#      args:
#        host: server
#        static_files_host: client
#        static_files_admin_host: admin
#        postgres_host: db
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      polis:
        ipv4_address: 192.168.1.6
#    networks:
#      - polis

  client:
    env_file:
      - env_dev
    build:
      context: ../polisClientParticipation
#    depends_on:
#     - db
#      - server
#    ports:
#      - 5001:5001
    expose:
      - 5001
    networks:
      polis:
        ipv4_address: 192.168.1.2
#    networks:
#      - polis

  admin:
    env_file:
      - env_dev
    build:
      context: ../polisClientAdmin
#    depends_on:
#     - db
#      - server
#    ports:
#      - 5002:5002
    expose:
      - 5002
    networks:
      polis:
        ipv4_address: 192.168.1.3

# networks:
#   polis:
#     driver: bridge
#     ipam:
#       driver: default

networks:
  polis:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
