version: "2.2"

services:
  db:
    env_file:
      - env_dev
    build:
      context: ../polisDatabase
    expose:
      - 5432
    networks:
      - polis

  server:
    env_file:
      - env_dev
    build:
      context: ../polisServer
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - polis

  math:
    env_file:
      - env_dev
    build:
      context: ../polisMath
    depends_on:
      - db
    networks:
      - polis

  client:
    env_file:
      - env_dev
    build:
      context: ../polisClientParticipation
    expose:
      - 5001
    networks:
      - polis

  admin:
    env_file:
      - env_dev
    build:
      context: ../polisClientAdmin
    expose:
      - 5002
    networks:
      - polis

# networks:
#   polis:
#     driver: bridge
#     ipam:
#       driver: default

networks:
  polis:
    external: false
    ipam:
      driver: default
