#!/usr/bin/env bash
# use ./<script> sudo if sudo is needed to run docker-compose (e.g. some ubuntu installations)
# use ./<script> if sudo is not needed
SUDO=$1
# copy configuration file templates
/bin/cp -f ../config/*template .
/bin/mv -f env_dev_template env_dev
/bin/mv -f polis.config.js_template polis.config.js
# modify configuration files if needed
sed -i 's/{{CLIENT_HOST}}/localhost/g' env_dev
sed -i 's/{{ADMIN_HOST}}/localhost/g' env_dev
sed -i 's/{{CLIENT_HOST}}/localhost/g' polis.config.js
sed -i 's/{{ADMIN_HOST}}/localhost/g' polis.config.js
sed -i 's|{{DATABASE_URL}}|postgres://postgres:postgres@localhost:5432/polis-dev|g' env_dev
sed -i 's|{{SERVICE_URL}}|http://localhost:5000|g' polis.config.js
# copy configuration files to code directories
/bin/cp -f env_dev ../polisServer
/bin/cp -f env_dev ../polisClientAdmin
/bin/cp -f env_dev ../polisClientParticipation
/bin/cp -f polis.config.js ../polisClientAdmin
/bin/cp -f polis.config.js ../polisClientParticipation
/bin/cp ../polisServer/postgres/db_setup_draft.sql ../polisDatabase/postgres
# remove temporary files
/bin/rm -f polis.config.js
/bin/rm -f env_dev
# build and run
$SUDO bash -c "(cd ../polisServer; docker container kill polis-server; docker container rm polis-server; docker image build -t polis-server:1.0 .; docker container run --env-file=env_dev  --network='host' --publish 5000:5000 --detach --name polis-server polis-server:1.0)"
$SUDO bash -c "(cd ../polisClientParticipation; docker container kill polis-client-participation; docker container rm polis-client-participation; docker image build -t polis-client-participation:1.0 .; docker container run --env-file=env_dev  --network='host' --publish 5001:5001 --detach --name polis-client-participation polis-client-participation:1.0)"
$SUDO bash -c "(cd ../polisClientAdmin; docker container kill polis-client-admin; docker container rm polis-client-admin; docker image build -t polis-client-admin:1.0 .; docker container run --env-file=env_dev  --network='host' --publish 5002:5002 --detach --name polis-client-admin polis-client-admin:1.0)"







