#!/usr/bin/env bash
# choose SUDO=sudo if sudo is needed to run docker-compose (e.g. some ubuntu installations)
# choose SUDO="" if sudo is not needed
SUDO=sudo
#SUDO=""
# clone necessary repos
BRANCH=docker_dgps
(cd ../..; git clone https://github.com/crkrenn/polis-deploy)
REPO=polisServer
(cd ../..; git clone https://github.com/crkrenn/${REPO})
(cd ../../${REPO}; git checkout ${BRANCH})
REPO=polisClientAdmin
(cd ../..; git clone https://github.com/crkrenn/${REPO})
(cd ../../${REPO}; git checkout ${BRANCH})
REPO=polisClientParticipation
(cd ../..; git clone https://github.com/crkrenn/${REPO})
(cd ../../${REPO}; git checkout ${BRANCH})
# copy necessary configuration files
cp polis.config_docker.js polisClientAdmin/polis.config.js
cp polis.config_docker.js polisClientParticipation/polis.config.js
cp polisServer/postgres/db_setup_draft.sql polisDatabase/postgres
${SUDO} ./dc-stop.sh
${SUDO} ./dc-start.sh
${SUDO} docker-compose logs -f




