version: "2.2"

services:
  db:
    env_file:
      - env_dev
    build:
      context: ./polisDatabase
    ports:
      - 5432:5432
    networks:
#      - backend
      - frontend

  server:
    env_file:
      - env_dev
    build:
      context: ./polisServer
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - frontend
#      - backend

  client:
    env_file:
      - env_dev
    build:
      context: ./polisClientParticipation
    ports:
      - 5001:5001
    networks:
      - frontend
#      - backend

  admin:
    env_file:
      - env_dev
    build:
      context: ./polisClientAdmin
    ports:
      - 5002:5002
    networks:
      - frontend
#      - backend

networks:
  frontend:
    driver: bridge
    ipam:
       driver: default
  backend:
    external: false
    ipam:
      driver: default
