extends:
  - eslint:recommended

env:
  es6: true
  node: true
  jest: true
  puppeteer: true

parserOptions:
  ecmaVersion: 9
  sourceType: module

globals:
  page: true
  context: true
  browser: true
  jestPuppeteer: true

rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  arrow-parens:
    - warn
    - as-needed
  object-curly-spacing:
    - warn
    - always
  no-multiple-empty-lines:
    - warn
    - max: 1
      maxEOF: 0
  space-before-function-paren:
    - warn
    - anonymous: always
      named: never
      asyncArrow: always
  semi: 2
  eqeqeq: 2
  eol-last: 1
  spaced-comment: 1
  no-multi-spaces: 1
  no-trailing-spaces: 1
  space-before-blocks: 1
  space-infix-ops: 1
  keyword-spacing: 1
  comma-spacing: 1
  key-spacing: 1
  no-console: 0
  comma-dangle: 0
  space-unary-ops: 0
  array-bracket-spacing: 0
