version: 1

task_definition:
  task_execution_role: $FARGATE_ROLE_NAME
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: $CONTAINER_MEMORY_LIMIT
    cpu_limit: $CONTAINER_CPU_LIMIT

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - $SUBNET_ID_1
        - $SUBNET_ID_2
      security_groups:
        - $GROUP_ID
      assign_public_ip: ENABLED
